export const products = [
  {
    id: 1,
    source: "/image1.jpeg",
    alt: "image1",
    name: "Undangan",
    category: "print lembaran",
    price: 5000,
  },
  {
    id: 2,
    source: "/image2.jpeg",
    alt: "image2",
    name: "Logo",
    category: "print lembaran",
    price: 4000,
  },
  {
    id: 3,
    source: "/image3.jpeg",
    alt: "image3",
    name: "Logo Banner",
    category: "Stationary",
    price: 8000,
  },
  {
    id: 4,
    source: "/image4.jpeg",
    alt: "image4",
    name: "Plank Pintu",
    category: "large format",
    price: 10000,
  },
  {
    id: 5,
    source: "/image5.jpeg",
    alt: "image5",
    name: "Stiker Tas",
    category: "marketing tools",
    price: 12000,
  },
  {
    id: 6,
    source: "/image6.jpeg",
    alt: "image6",
    name: "Booklet",
    category: "print lembaran",
    price: 22000,
  },
  {
    id: 7,
    source: "/image7.jpeg",
    alt: "image7",
    name: "Stiker Tas Variasi",
    category: "print lembaran",
    price: 15000,
  },
  {
    id: 8,
    source: "/image8.jpeg",
    alt: "image8",
    name: "Stiker Cap",
    category: "UMKM",
    price: 2000,
  },
  {
    id: 9,
    source: "/image9.jpeg",
    alt: "image5",
    name: "Piagam",
    category: "Promo and Gift",
    price: 120000,
  },
];
